import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #435469;
    in property <string> version;
    in property <int> progress: 0;
    callback download_pressed();
    width: 1000px;
    height: 600px;
    Rectangle {
        background: #333333;
        width: 250px;
        x: 0px;
        Rectangle {
            height: 80px;
            width: 250px;
            x: 0px;
            y: 0px;
            Text {
                font-size: 16px;
                font-weight: 600;
                text: "Bienvenido a Minecraft Canadá";
                x: 10px;
                y: 10px;
            }

            Image {
                //Canada logo
            }
        }
    }

    Image {
        width: 200px;
        x: 402px;
        y: 71px;
        height: 200px;
        source: @image-url("./minecraft_img.png");
        image-fit: fill;
    }

    Text {
        text: "Version: \{version}";
        x: 849px;
        y: 576px;
    }

    Rectangle {
        VerticalLayout {
            HorizontalLayout {
                alignment: center;
                Button {
                    text: "Descargar";
                    height: 30px;
                    clicked => {
                        root.download_pressed();
                    }
                }
            }

            Rectangle {
                width: 80%;
                height: 30px;
                border-width: 1px;
                border-color: white;
                Rectangle {
                    width: parent.width * (root.progress / 100);
                    height: parent.height;
                    background: green;
                }
            }
        }

        width: 400px;
        x: 294px;
        y: 490px;
        height: 60px;
    }
}
